### ISSUE TITLE
"Locked/Unlocked <item_name>" message not localized

### ISSUE THREAD

**Issue by cowgod** [designker/ishtar-commander-bugs#112] opened 2016-08-01 15:38 UTC
When locking or unlocking an item, the word "Locked" or "Unlocked" in the status message that appears in the black bar at the bottom of the screen is not localized.

![image](https://cloud.githubusercontent.com/assets/523086/17299484/81714218-57dc-11e6-985e-38aaacd43f92.png)

**Comment by lostyBO** [comment] 2016-08-04 06:20
Fixed in build 596 because it now only shows the item name in the bottom bar?!

**Comment by floatingatoll** [comment] 2016-08-07 22:58
Confirmed that in build 603, it only shows the item name and not localized "locked" or "unlocked".

**Comment by designker** [comment] 2016-08-08 11:52
fixed

**Closed by designker** 2016-08-08 11:52 UTC
Labels: localization
