### ISSUE TITLE
Style for stats view is different for items in Postmaster

### ISSUE THREAD

**Issue by alexxnz** [designker/ishtar-commander-bugs#325] opened 2017-11-11 07:34 UTC
Specifically, the intrinsic perk block is normally shaded lighter than the rest of the pop-up in stats view. However, for items in the Postmaster, the intrinsic perk block is shaded the same color as the rest of the pop-up. (Beta 140)

See #324 for how this looks in-app

**Comment by designker** [comment] 2017-12-29 17:38
Dupe of #324 and waiting for a bungie fix

**Closed by designker** 2017-12-29 17:38 UTC
