### ISSUE TITLE
Item switching in loadouts

### ISSUE THREAD

**Issue by bam3339** [designker/ishtar-commander-bugs#201] opened 2016-11-21 18:33 UTC
After saving a loadout, when going back in to view the loadout through the edit feature the weapon I selected as the one to equip will be switched with one that wasn't.

For example, I select a Matador 64 as the equipped secondary and a Saladins Vigil as another secondary to transfer.  When I go back in to view the loadout, they have been swapped.  I've also seen this occur with primary weapons as well (I have one clever dragon that I select as my equipped, and another that I just wanted also transfer, but they will be reversed after saving).  I have a recording from the first one occuring on my phone (email me directly if you need to see it and I will send it).

Using Android 6.0 on Moto X Pure with build 728 of IC.  I have a friend who uses the app on iPhone and he has mentioned this happening to him also.

**Comment by RedHotTrouble** [comment] 2017-06-07 07:18
@bam3339 are you still able to replicate this issue with the latest Beta Build 849?

I tried in iPhone 7 but I can't reproduce this when loading or editing a loadout. The equipped and unequipped weapons show in their respective saved slots.

@designker Were you ever able to replicate this on Android? And/or have you addressed this? Since this was creared so long ago, I'm wondering if this still an open bug. 🤔

**Comment by designker** [comment] 2017-06-07 08:44
Just leave it. Loadouts are buggy as hell and will be rewitten one day

**Comment by designker** [comment] 2017-08-06 21:12
Will be fixed for D2

**Closed by designker** 2017-08-06 21:12 UTC
