### ISSUE TITLE
Automatically transfer consumables & materials to active character

### ISSUE THREAD

**Issue by cowgod** [designker/ishtar-commander-bugs#18] opened 2016-05-20 20:02 UTC
Implement functionality to transfer commonly-needed consumables & materials to the actively logged-in character. This could be a one-time-use button on the character's loadout screen, like "Maximize Light", or a mode you can toggle on to do this automatically on every 30-second refresh.

There could be separate buttons for the various situations you might find yourself in, and the items needed in each situation:

**Play**
- Three of Coins
- 3x Ammo synths

**Leveling/Infusion**
- Motes of light
- 5x Planetary materials
- Weapon parts
- Armor parts
- Exotic shards
- Glass needles
- Chroma (maybe?)

**Comment by jmartin657** [comment] 2016-05-31 15:13
I would prefer to be able to pick and choose what items are transferred automatically (like glimmer items sent directly to vault) but honestly I would be glad to make anything transfer automatically -_- its tedious at the moment

**Comment by designker** [comment] 2016-07-03 10:13
Not a bug

**Closed by designker** 2016-07-03 10:13 UTC

**Comment by jmartin657** [comment] 2016-07-04 12:38
http://media.tumblr.com/tumblr_m9bxv9aTbm1qcrima.jpg
