### ISSUE TITLE
scrolling images not shoving for 2 characters

### ISSUE THREAD

**Issue by wallycoelho** [designker/ishtar-commander-bugs#2] opened 2016-01-23 00:54 UTC
build: 305
on the hunter(middle) and titan(right) when i select a loadout the images of the items do not scroll on the right. it does on the left character a warlock.

**Comment by designker** [comment] 2016-01-23 00:57
Can you add a screenshot?

**Comment by wallycoelho** [comment] 2016-01-23 00:58
i don't see a option for that on the mobile. i will check on the  desktop

**Comment by wallycoelho** [comment] 2016-01-23 01:08
video https://drive.google.com/file/d/0B3q2G7oHplYSX2hJcWtGSGpMVk0/view?usp=docslist_api

**Comment by alexxnz** [comment] 2016-01-23 07:31
I believe that's by design. The item animations only occur for your active character (the one you're  currently using or last logged in with)

You can tell which one is active by looking for the fireteam lead icon (yellow triangle) on the character's emblem.

**Comment by designker** [comment] 2016-01-23 11:09
Works as specified. The animated spinners are only shown when items are transferred to the last active character.

**Closed by designker** 2016-01-23 11:09 UTC

**Comment by wallycoelho** [comment] 2016-01-23 13:28
oh ok. it was not so before build 305. that is why i reported it.

On Sat, Jan 23, 2016, 6:09 AM Nigel Hietala <notifications@github.com>
wrote:

> Works as specified. The animated spinners are only shown when items are
> transferred to the last active character.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/designker/ishtar-commander-bugs/issues/2#issuecomment-174171833>
> .
>
-- 
Warlley S. Coelho
www.warlleycoelho.com
www.facebook.com/WarlleyCoelhoPhotography
"Don't show GOD the size of your problems, Show your problems the size of
your GOD !"
