### ISSUE TITLE
Postmaster gun shows selectable perk node

### ISSUE THREAD

**Issue by alexxnz** [designker/ishtar-commander-bugs#170] opened 2016-10-04 23:12 UTC
This is possibly related to issue #168, but noticed this with a gun I have waiting for me in the Postmaster

![screenshot_20161004-013201](https://cloud.githubusercontent.com/assets/16849366/19095842/59b345c0-8a66-11e6-8dd3-0b2294beb391.png)

**Comment by alexxnz** [comment] 2016-10-04 23:22
Just noticed a few more Postmaster guns have this issue. The last two have been in my Postmaster since before Rise of Iron was released. I also have a Havoc Pigeon in Postmaster that displays the perk nodes correctly.

![screenshot_20161004-191927](https://cloud.githubusercontent.com/assets/16849366/19096075/cef7f3e8-8a67-11e6-8976-a7d92b370fbb.png)
![screenshot_20161004-191935](https://cloud.githubusercontent.com/assets/16849366/19096077/cef8b760-8a67-11e6-9a12-20eb9e4728ee.png)
![screenshot_20161004-191938](https://cloud.githubusercontent.com/assets/16849366/19096076/cef87426-8a67-11e6-9e3c-0a5be9a0487b.png)

**Comment by tehtrav** [comment] 2016-10-05 16:49
I'm also getting some weird perk tree results. See these two weapons compared to DIM which displays their perks correctly.

![group](https://cloud.githubusercontent.com/assets/351975/19122799/1c17a582-8afa-11e6-8aba-ad859c12eddf.png)

**Comment by designker** [comment] 2016-10-05 16:51
Dupe of https://github.com/designker/ishtar-commander-bugs/issues/168

**Closed by designker** 2016-10-05 16:51 UTC
