### ISSUE TITLE
Tapping weapons then armor goes to weapons

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#224] opened 2017-05-14 15:52 UTC
Sometime my hands spasm and hit the wrong one, but when I correct and hit armor, it ignores me and continues fading in weapons.

**Comment by RedHotTrouble** [comment] 2017-06-07 06:57
@designker I'm curious if there's actually a way for you to address this. I can't really replicate it unless I use my two thumbs to almost simultaneously hit both sections. Clearly the latter section can't be triggered until the first section has been "loaded" (scrolled to). But this looks like standard / expected behavior to me. 

If it's not standard/expected, the only thing I'd try is changing the visual effect of the unselectable sections (to show as unselectable/unclickable) while the scroll effect is taking place. But I'm not sure if that's doable, or if it's a high enough priority that's worth trying/addressing.

*** Side note: I'm going through open bugs to see what may have already been addressed with the latest build and can be closed. If you guys would prefer I disregard bugs I haven't created, please let me know! 🙃

**Comment by floatingatoll** [comment] 2017-06-07 07:00
I would take a guess that the pane-flip animation causes further taps until
it's complete, rather than interrupting to proceed to the latest tap.

**Comment by RedHotTrouble** [comment] 2017-06-07 08:16
This particular case reminded me of race conditions I've experienced in other UI scripting languages like JavaScript. Some asynchronous events seem to get lost depending on how they're coded because one action takes some time to be completed, while the other one was simultaneously triggered.

This is why I wanted to ask @designker if with Zing Studio's scripting language this can be accomplished: interrupt the scroll-down action, while it's already happening and before it's completed, in order for the next immediate (and almost simultaneous) action to take effect.

In jQuery, something like e.preventDefault() and e.stopPropagation() is used to stop all other event handlers before an action begins. Perhaps similar logic is what's causing the current behavior; which would make sense when there's an animation, being that a scrolling effect isn't instant. This helps avoid unexpected / inconsistent / unreliable, and ugly behaviors caused by race conditions.

So if this was the intended behavior, my next suggestion would be to make the user aware (through any form of visual effect) that the other tabs can't be clicked until the first action is completed; so the expected behavior or limitation is more clear to the end-user.

**Comment by designker** [comment] 2017-06-11 17:40
Not fixed 100% but reduced as an issue, so I am closing this

**Closed by designker** 2017-06-11 17:40 UTC
