### ISSUE TITLE
Shaders aren’t stacked at vault transfer leading to 203/200 count

### ISSUE THREAD

**Issue by floatingatoll** [designker/ishtar-commander-bugs#330] opened 2017-12-22 10:09 UTC
I had the same shader in Inventory and vault, when I transferred to full vault, ended up at 201/200. Highest I got was 204/200, screenshot if you need it

**Comment by designker** [comment] 2017-12-29 17:40
May not seem it but this is a dupe of #270

**Closed by designker** 2017-12-29 17:40 UTC
